### ISSUE TITLE
Sparse multiplication with different sized basis

### ISSUE THREAD

**Issue by AmitRotem** [qojulia/QuantumOpticsBase.jl#74] opened 2022-11-29 22:46 UTC
sparse multiplication with different sized basis
```
mul!(randstate(NLevelBasis(5)),
  sparse(randoperator(NLevelBasis(4))),
  randstate(NLevelBasis(3))
  ) # runs with no errors

mul!(randoperator(NLevelBasis(6)),
  randoperator(NLevelBasis(4)),
  sparse(randoperator(NLevelBasis(3)))
  ) # runs with no errors
```

**Comment by amilsted** [comment] 2022-11-29 23:13
Yeah, currently I think there is only a basis type restriction here. I am guessing the `N` of `NLevelBasis` is not a type parameter, so we don't catch the difference. Maybe we should do some explicit basis checks here too...

**Comment by amilsted** [comment] 2022-11-29 23:16
Wait... how is this even possible? Don't these bases have different dimensions??

**Comment by amilsted** [comment] 2022-11-29 23:25
There's some other weird stuff in `sparsematrix.jl`, including a 3-arg version of `permutedims()` that should probably *not* extend `Base.permutedims()`. The `ptrace()` method is also suspicious-looking.

**Comment by amilsted** [comment] 2022-11-29 23:25
@david-pl can you remind me if there were any benchmarks suggesting the homemade sparse `gemm` routines are faster than those in the standard library?

**Comment by david-pl** [comment] 2022-11-30 20:23
Oh, that's worrying. If I remember correctly, I was simply relying on basis type checks because I figured the multiplication methods would check dimension anyway. But I guess this one doesn't.

@amilsted I remember benchmarking this when loosening type constraints. Benchmarks suggested that the homemade methods here were faster at least some of the time (I did not check scaling for growing matrix sizes), so I just stuck with these methods as to not introduce any regressions with my changes. I'm open to changing this, of course, and in the long-term this should definitely be replaced by the standard library methods.

If we do find something that's actually more efficient we should discuss upstreaming it.

**Comment by amilsted** [comment] 2022-11-30 23:12
@david-pl I don't have anything more efficient, but one advantage of using the standard sparse-matrix `mul!()` methods is that you can load `MKLSparse` to get threaded sparse mat-mat.

**Comment by amilsted** [comment] 2022-11-30 23:15
In any case, the obvious fix is to add dimension checks to the gemm routines.

**Comment by amilsted** [comment] 2023-01-11 14:23
@david-pl Regarding using the SparseArrays `mul!` routines, perhaps we could have a global configuration setting that switches sparse ops to use SparseArrays `mul!` instead of the home-grown methods. This way we could more easily do performance comparisons. Probably accessing a global boolean with each mul isn't a lot of overhead...

**Comment by AmitRotem** [comment] 2023-03-21 23:31
Just stumbled on another case where with sparse dense multiplication should fail but doesn't
```
b1=NLevelBasis(1)
b2=NLevelBasis(3)
h = LazyTensor(b1^2, b2^2, 2, sparse(randoperator(b1, b2)))
dense(h)*h # runs with no errors
```

https://github.com/qojulia/QuantumOpticsBase.jl/pull/83 did not fix this case.

**Comment by amilsted** [comment] 2023-03-21 23:38
Oh dear, guess we don't have checks in the LazyTensor sparse code either! @AmitRotem, do you want to add them in your open PR?

**Comment by AmitRotem** [comment] 2023-03-21 23:44
Sure

**Comment by amilsted** [comment] 2023-04-23 17:57
Should be fixed now?

**Closed by amilsted** 2023-04-23 17:57 UTC
